var translationsEN = {
    car_code:'Car Code',
	brand:'Brand'      ,
	model:'Model'      ,
	color: 'Color'     ,
	year: 'Year'       ,
	price:'Price'      ,
	description:'Description',
	is_new:'Is new?'   ,
	registration_date:'Registration Date',
	update_date:'Update Date',
	yes:'Yes'          ,
    no:'No'            ,
	exit:'Log out'     ,
	language:'Language',
	start:'Start'      ,
	car:'Car'          ,
	registers:'Registers',
	header_register_car:"CRUD - Vehicle Registration",
	register_car:'Vehicle Registration',
	save:'Save'        ,
	delete:'Delete'    ,
	new:'New'          ,
	options:'Options'  ,
	no_record_available: 'No record available!',
	record_already_registered:'Search for a record already registered.'
};
 
var translationsPT= {  
  	car_code:'Código do Veículo',
	brand:'Marca'           ,
	model:'Modelo'          ,
	color: 'Cor'            ,
	year: 'Ano'             ,
	price:'Preço'           ,
	description:'Descrição' ,
	is_new:'Veículo Novo?'  ,
	registration_date:'Data de Cadastro',
	update_date:'Data de Atualização',
	yes:'Sim'               ,
    no:'Não'                ,
	exit:'Sair'             ,
	language:'Idioma'       ,
	start:'Início'          ,
	car:'Veículo'           ,
	registers:'Cadastros'   ,
	header_register_car:"CRUD - Cadastro de Veículos",
	register_car:'Cadastro de Veículos',
	save:'Salvar'           ,
	delete:'Excluir'        ,
	new:'Novo'              ,  
	options:'Opções'        ,
	no_record_available: 'Nenhum registro disponível!',
	record_already_registered:'Pesquisar um registro já cadastrado.'
};